--- 
networks: 
  ttn: 
services: 
  tomcat-test: 
    container_name: tomcat-test1
    hostname: tomcat-test
    image: dockerttn/tomcat
    networks: 
      ttn:
    ports: 
      - "8080:8080"
    healthcheck:
        test: ["CMD", "curl","-f", "http://tomcat-test:8080/sample"]
        interval: 30s
        timeout: 2s
        retries: 1
  nginxproxy-test:
   image: nginx  #assign a name to the built image
   container_name: nginxproxy-test
   volumes:
    - "./default.conf:/etc/nginx/conf.d/default.conf"
   hostname: nginxproxy-test
   networks:
      ttn:
   ports:
    - "80:80"
version: '3.1'

